name:                elm-language-server
version:             0.0.1
github:              "jaredramirez/elm-language-server"
license:             BSD3
author:              "Jared Ramirez"
maintainer:          "jaredramirez@me.com"
copyright:           "2018 Jared Ramirez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jaredramirez/elm-language-server#readme>

dependencies:
- base >= 4.8 && < 5
- text
- aeson
- aeson-utils
- unordered-containers
- bytestring
- directory
# For Elm Parser
- ansi-terminal >= 0.8 && < 0.9
- ansi-wl-pprint >= 0.6.8 && < 0.7
- containers >= 0.5.8.2 && < 0.6
- scientific
- binary >= 0.8 && < 0.9
- vector
- filepath >= 1 && < 2.0
- utf8-string
- parsec
- language-glsl >= 0.0.2 && < 0.3

library:
  source-dirs:
  - src
  - elm
  other-extensions:
  - TemplateHaskell

executables:
  elm-language-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-language-server

tests:
  elm-language-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-language-server
